apiVersion: v1
kind: Secret
metadata:
  name: stock-secret
type: Opaque
stringData:
    appsettings.Development.json: |-
      {
        "Logging": {
          "LogLevel": {
            "Default": "Information",
            "Microsoft.AspNetCore": "Warning"
          }
        }
      }
