cloudse:
  deployment:
    database:
      parent:
        host:
          host: "$env{DB_HOST}"
          environmentVariable: "DB_HOST"
        port: "5432"
        driver: "org.postgresql.Driver"
      mainDB:
        url:
          url: "http://database-1.cfv10rew3vrj.us-east-1.rds.amazonaws.com/"
          environmentVariable: "MAIN_DB_URL"
        dbName: "cloudse_main_db"
        username:
          username: "postgres"
          environmentVariable: "MAIN_DB_USERNAME"
        password:
          password: "isuruCcamsciit"
          environmentVariable: "MAIN_DB_PASSWORD"

    imagePull:
      # Image related
      # Customer private repo
      privateRegistry:
        enabled: true
        dockerRegistry: "url.com"
        imageName: "cloudse"
        imageTag: "1.0.0-alpine-"

      # Refer to the Kubernetes documentation on updating images (https://kubernetes.io/docs/concepts/containers/images/#updating-images)
      imagePullPolicy: Always

    spec:
      # Number of deployment replicas
      replicas: 1
      # Minimum number of seconds for which a newly created pod should be ready without any of its containers crashing, for it to be considered available.
      minReadySeconds: 30
      strategy:
        rollingUpdate:
          # The maximum number of pods that can be scheduled above the desired number of pods.
          maxSurge: 1
          # The maximum number of pods that can be unavailable during the update.
          maxUnavailable: 1

      # Kubernetes Probes
      # Startup probe executed prior to Liveness Probe taking over
      startupProbe:
        # Number of seconds after the container has started before startup probes are initiated
        initialDelaySeconds: 100
        # How often (in seconds) to perform the probe
        periodSeconds: 10
        # Number of attempts
        failureThreshold: 30
      # Indicates whether the container is running.
      livenessProbe:
        # Number of seconds after the container has started before liveness probes are initiated.
        initialDelaySeconds: 100
        # How often (in seconds) to perform the probe.
        periodSeconds: 10
      # Indicates whether the container is ready to service requests.
      readinessProbe:
        # Number of seconds after the container has started before readiness probes are initiated.
        initialDelaySeconds: 100
        # How often (in seconds) to perform the probe.
        periodSeconds: 10

      resources:
        # These are the minimum resource recommendations for running CloudSE product
        requests:
          # The minimum amount of memory that should be allocated for a Pod
          memory: "4Gi"
          # The minimum amount of CPU that should be allocated for a Pod
          cpu: "2000m"
        limits:
          # The maximum amount of memory that should be allocated for a Pod
          memory: "4Gi"
          # The maximum amount of CPU that should be allocated for a Pod
          cpu: "2000m"

    configCm:
        mapname: "client-cloudse-pattern-config-param"
        deploymentVolumeName: "cloudse-config"

# Kubernetes specific
kubernetes:
  # Namespace to be released in
  releaseNamespace: 
    namespace: "cloudse"
    environmentVariable: "KUBERNETES_NAMESPACE"
  prefix: "client-cloudse-pattern"